{{- if .Values.agentAi.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agentAi.name }}-secret
  labels:
    {{- include "pulse-performance-management.agentAi.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.agentAi.databasePassword }}
  database-password: {{ .Values.secrets.agentAi.databasePassword | b64enc }}
  {{- else }}
  database-password: {{ "changeme" | b64enc }}
  {{- end }}
  {{- if .Values.secrets.agentAi.googleCloudProject }}
  google-cloud-project: {{ .Values.secrets.agentAi.googleCloudProject | b64enc }}
  {{- else }}
  google-cloud-project: {{ "" | b64enc }}
  {{- end }}
  {{- if .Values.secrets.agentAi.googleApiKey }}
  google-api-key: {{ .Values.secrets.agentAi.googleApiKey | b64enc }}
  {{- else }}
  google-api-key: {{ "" | b64enc }}
  {{- end }}
  {{- if .Values.secrets.agentAi.jwtSecretKey }}
  jwt-secret-key: {{ .Values.secrets.agentAi.jwtSecretKey | b64enc }}
  {{- else }}
  jwt-secret-key: {{ "changeme" | b64enc }}
  {{- end }}
{{- end }}

